name: Check for new upstream tag and update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Every day at 12am

jobs:
  check-for-new-tag:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get latest tag for upstream image
        run: |
          echo "LATEST_VERSION=$(./scripts/get-latest-tag.sh | tee version)" | tee -a $GITHUB_ENV
      - name: Check if version file has changed
        id: version-changed
        uses: tj-actions/changed-files@v39
        with:
          files: version
      - name: Commit if version changed
        if: steps.version-changed.outputs.any_changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated version to $LATEST_VERSION
